# Generated by Django 4.1.3 on 2022-12-23 11:32

from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editor):
    User = apps.get_model("core", "User")
    Board = apps.get_model("goals", "Board")
    BoardParticipant = apps.get_model("goals", "BoardParticipant")
    GoalCategory = apps.get_model("goals", "GoalCategory")

    with transaction.atomic():
        now = timezone.now()
        for user in User.objects.values_list('id', flat=True):
            new_board = Board(title='Мои цели', created=now, updated=now)
            BoardParticipant.objects.create(user=user, board=new_board, role=1, created=now, updated=now)
            GoalCategory.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0004_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
